### ISSUE TITLE
train 

### ISSUE THREAD

**Issue by qqhe-frank** [cosmic-cortex/pytorch-UNet#14]
![image](https://user-images.githubusercontent.com/71333170/110738378-24c58200-826a-11eb-999c-0cfa860bbfd0.png)
How do i solve this kind of problem，Is it because of my own data set?

**Comment by HoraceXIaoyiBao** [comment]
change the out put channel to 256 in train.py

**Comment by TillmannRheude** [comment]
In case you are doing binary segmentation: Check if your target (mask) values are 0 and 255 instead of 0 and 1. If they're 0 and 255, go to the ImageToImage2D class and convert the masks:
`mask = np.array(mask)`
`mask = mask / 255`
`mask = mask.astype("uint8")`

**Comment by qqhe-frank** [comment]
Thanks, It's for working for me.
